### Advanced Fucntions of Pandas

* The following file will helps us to know the advance functions of Pandas which help us to reduce the memory intake and ease our effort to get desired output from the dataset.
* Generally these functions allows us to combine various datacolumns adn rows and explain the relation between the inputs of the dataset.

***Import necessary libraries***

In [1]:
import pandas as pd 
!pip install xlrd

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xlrd in c:\users\gkris\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (2.0.1)

***Read the file***

In [2]:
df = pd.read_excel("E:\Machine Learning\global_superstore\Global Superstore.xls")
print(df)

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\gkris\AppData\Local\Temp\ipykernel_24440\2825614032.py:1: SyntaxWarning: invalid escape sequence '\M'
  df = pd.read_excel("E:\Machine Learning\global_superstore\Global Superstore.xls")

       Row ID         Order ID Order Date  Ship Date       Ship Mode  \
0       32298   CA-2012-124891 2012-07-31 2012-07-31        Same Day
1       26341    IN-2013-77878 2013-02-05 2013-02-07    Second Class
2       25330    IN-2013-71249 2013-10-17 2013-10-18     First Class
3       13524  ES-2013-1579342 2013-01-28 2013-01-30     First Class
4       47221     SG-2013-4320 2013-11-05 2013-11-06        Same Day
...       ...              ...        ...        ...             ...
51285   29002    IN-2014-62366 2014-06-19 2014-06-19        Same Day
51286   35398   US-2014-102288 2014-06-20 2014-06-24  Standard Class
51287   40470   US-2013-155768 2013-12-02 2013-12-02        Same Day
51288    9596   MX-2012-140767 2012-02-18 2012-02-22  Standard Class
51289    6147   MX-2012-134460 2012-05-22 2012-05-26    Second Class

      Customer ID     Customer Name      Segment           City  \
0        RH-19495       Rick Hansen     Consumer  New York City
1        JR-16210     Justin Ritter    Corporate     Wollongong
2        CR-12730      Craig Reiter     Consumer       Brisbane
3        KM-16375  Katherine Murray  Home Office         Berlin
4         RH-9495       Rick Hansen     Consumer          Dakar
...           ...               ...          ...            ...
51285    KE-16420   Katrina Edelman    Corporate           Kure
51286    ZC-21910  Zuschuss Carroll     Consumer        Houston
51287    LB-16795    Laurel Beltran  Home Office         Oxnard
51288    RB-19795        Ross Baird  Home Office       Valinhos
51289    MC-18100     Mick Crebagga     Consumer       Tipitapa

                 State  ...        Product ID         Category Sub-Category  \
0             New York  ...   TEC-AC-10003033       Technology  Accessories
1      New South Wales  ...   FUR-CH-10003950        Furniture       Chairs
2           Queensland  ...   TEC-PH-10004664       Technology       Phones
3               Berlin  ...   TEC-PH-10004583       Technology       Phones
4                Dakar  ...  TEC-SHA-10000501       Technology      Copiers
...                ...  ...               ...              ...          ...
51285        Hiroshima  ...   OFF-FA-10000746  Office Supplies    Fasteners
51286            Texas  ...   OFF-AP-10002906  Office Supplies   Appliances
51287       California  ...   OFF-EN-10001219  Office Supplies    Envelopes
51288        São Paulo  ...   OFF-BI-10000806  Office Supplies      Binders
51289          Managua  ...   OFF-PA-10004155  Office Supplies        Paper

                                            Product Name     Sales Quantity  \
0      Plantronics CS510 - Over-the-Head monaural Wir...  2309.650        7
1              Novimex Executive Leather Armchair, Black  3709.395        9
2                      Nokia Smart Phone, with Caller ID  5175.171        9
3                         Motorola Smart Phone, Cordless  2892.510        5
4                         Sharp Wireless Fax, High-Speed  2832.960        8
...                                                  ...       ...      ...
51285                      Advantus Thumb Tacks, 12 Pack    65.100        5
51286  Hoover Replacement Belt for Commercial Guardsm...     0.444        1
51287       #10- 4 1/8" x 9 1/2" Security-Tint Envelopes    22.920        3
51288                            Acco Index Tab, Economy    13.440        2
51289            Eaton Computer Printout Paper, 8.5 x 11    61.380        3

      Discount    Profit  Shipping Cost  Order Priority
0          0.0  762.1845        933.570        Critical
1          0.1 -288.7650        923.630        Critical
2          0.1  919.9710        915.490          Medium
3          0.1  -96.5400        910.160          Medium
4          0.0  311.5200        903.040        Critical
...        ...       ...            ...             ...
51285      0.0    4.5000          0.010          Medium
51286      0.8   -1.1100          0.010          Medium
51287      0.0   11.2308          0.010            High
51288      0.0    2.4000          0.003          Medium
51289      0.0    1.8000          0.002            High

[51290 rows x 24 columns]

***Performing Basic Analysis***

In [3]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'City', 'State', 'Country',
       'Postal Code', 'Market', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'],
      dtype='object')

In [4]:
df.shape

(51290, 24)

In [6]:
df.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
City                      object
State                     object
Country                   object
Postal Code              float64
Market                    object
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
Shipping Cost            float64
Order Priority            object
dtype: object

In [7]:
df.isnull().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
City                  0
State                 0
Country               0
Postal Code       41296
Market                0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [9]:
df.describe(include = "all")

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
count,51290.00000,51290,51290,51290,51290,51290,51290,51290,51290,51290,...,51290,51290,51290,51290,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290
unique,NaN,25035,NaN,NaN,4,1590,795,3,3636,1094,...,10292,3,17,3788,NaN,NaN,NaN,NaN,NaN,4
top,NaN,CA-2014-100111,NaN,NaN,Standard Class,PO-18850,Muhammed Yedwab,Consumer,New York City,California,...,OFF-AR-10003651,Office Supplies,Binders,Staples,NaN,NaN,NaN,NaN,NaN,Medium
freq,NaN,14,NaN,NaN,30775,97,108,26518,915,2001,...,35,31273,6152,227,NaN,NaN,NaN,NaN,NaN,29433
mean,25645.50000,NaN,2013-05-11 21:26:49.155781120,2013-05-15 20:42:42.745174528,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,246.490581,3.476545,0.142908,28.610982,26.375818,NaN
min,1.00000,NaN,2011-01-01 00:00:00,2011-01-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.444000,1.000000,0.000000,-6599.978000,0.002000,NaN
25%,12823.25000,NaN,2012-06-19 00:00:00,2012-06-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,30.758625,2.000000,0.000000,0.000000,2.610000,NaN
50%,25645.50000,NaN,2013-07-08 00:00:00,2013-07-12 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,85.053000,3.000000,0.000000,9.240000,7.790000,NaN
75%,38467.75000,NaN,2014-05-22 00:00:00,2014-05-26 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,251.053200,5.000000,0.200000,36.810000,24.450000,NaN
max,51290.00000,NaN,2014-12-31 00:00:00,2015-01-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,22638.480000,14.000000,0.850000,8399.976000,933.570000,NaN
std,14806.29199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,487.565361,2.278766,0.212280,174.340972,57.296810,NaN

***Performing Advanced Functions***

* The below codes were used to know select the specific columns of the datasets and these codes need correct syntax to perform the function which will take some time ,so to ease our difficulties in performance advance functions are applied.

In [10]:
df[["Segment","City","State"]]

           Segment           City            State
0         Consumer  New York City         New York
1        Corporate     Wollongong  New South Wales
2         Consumer       Brisbane       Queensland
3      Home Office         Berlin           Berlin
4         Consumer          Dakar            Dakar
...            ...            ...              ...
51285    Corporate           Kure        Hiroshima
51286     Consumer        Houston            Texas
51287  Home Office         Oxnard       California
51288  Home Office       Valinhos        São Paulo
51289     Consumer       Tipitapa          Managua

[51290 rows x 3 columns]

In [11]:
df[(df["Segment"]== "Consumer") & (df["Category"] == "Technology")]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical
12,45794,SA-2011-1830,2011-12-27,2011-12-29,Second Class,MM-7260,Magdelene Morse,Consumer,Jizan,Jizan,...,TEC-CIS-10001717,Technology,Phones,"Cisco Smart Phone, with Caller ID",2616.960,4,0.0,1151.4000,832.41,Critical
21,31784,CA-2011-154627,2011-10-29,2011-10-31,First Class,SA-20830,Sue Ann Reed,Consumer,Chicago,Illinois,...,TEC-PH-10001363,Technology,Phones,Apple iPhone 5S,2735.952,6,0.2,341.9940,752.51,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50885,40460,CA-2012-164007,2012-06-08,2012-06-12,Standard Class,MG-17695,Maureen Gnade,Consumer,Chicago,Illinois,...,TEC-AC-10003433,Technology,Accessories,Maxell 4.7GB DVD+R 5/Pack,2.376,3,0.2,0.7425,0.18,Medium
51007,44682,SO-2011-1410,2011-12-16,2011-12-21,Standard Class,CS-1860,Cari Schnelling,Consumer,Hargeysa,Woqooyi Galbeed,...,TEC-MEM-10001163,Technology,Accessories,"Memorex Mouse, Erganomic",25.980,1,0.0,1.0200,0.15,Medium
51095,45007,KZ-2011-7910,2011-07-20,2011-07-20,Same Day,MM-8055,Michelle Moray,Consumer,Pavlodar,Pavlodar,...,TEC-LOG-10002589,Technology,Accessories,"Logitech Memory Card, USB",31.077,1,0.7,-55.9530,0.12,Medium
51143,39197,CA-2014-128363,2014-08-14,2014-08-19,Standard Class,DC-12850,Dan Campbell,Consumer,Memphis,Tennessee,...,TEC-AC-10003709,Technology,Accessories,Maxell 4.7GB DVD-R 5/Pack,1.584,2,0.2,0.4752,0.10,Medium
51178,47992,SU-2014-3390,2014-01-02,2014-01-06,Standard Class,JM-5250,Janet Martin,Consumer,Bur Sudan,Red Sea,...,TEC-MOT-10001088,Technology,Phones,"Motorola Audio Dock, VoIP",173.460,1,0.0,50.2800,0.09,Medium

In [16]:
df[(df["State"]== "California") & (df["Product Name"] == "Staples")]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
23366,37200,US-2014-153948,2014-11-07,2014-11-07,Same Day,FM-14290,Frank Merwin,Home Office,San Francisco,California,...,OFF-PA-10002764,Office Supplies,Paper,Staples,45.360,4,0.0,22.2264,9.40,Critical
25447,38763,CA-2013-138282,2013-05-20,2013-05-24,Standard Class,AH-10690,Anna Häberlin,Corporate,Los Angeles,California,...,OFF-AP-10001366,Office Supplies,Appliances,Staples,87.840,8,0.0,23.7168,7.92,High
25654,34161,US-2014-103828,2014-08-14,2014-08-14,Same Day,JK-15370,Jay Kimmel,Consumer,San Francisco,California,...,OFF-AP-10004249,Office Supplies,Appliances,Staples,83.790,7,0.0,22.6233,7.79,High
26146,37107,US-2012-163279,2012-03-22,2012-03-26,Standard Class,JD-16150,Justin Deggeller,Corporate,San Diego,California,...,OFF-PA-10003127,Office Supplies,Paper,Staples,105.520,4,0.0,48.5392,7.50,Medium
27021,38823,US-2014-106145,2014-09-27,2014-09-27,Same Day,RA-19885,Ruben Ausman,Corporate,San Francisco,California,...,OFF-EN-10001028,Office Supplies,Envelopes,Staples,71.880,6,0.0,33.0648,6.98,Medium
29254,33680,US-2014-117534,2014-03-26,2014-03-27,First Class,CV-12295,Christina VanderZanden,Consumer,Fresno,California,...,OFF-AR-10003087,Office Supplies,Art,Staples,16.020,9,0.0,4.4856,5.85,Critical
30207,34163,US-2014-103828,2014-08-14,2014-08-14,Same Day,JK-15370,Jay Kimmel,Consumer,San Francisco,California,...,OFF-SU-10000946,Office Supplies,Supplies,Staples,31.920,4,0.0,9.2568,5.40,High
31382,39299,CA-2012-110870,2012-12-12,2012-12-15,First Class,KD-16270,Karen Daniels,Consumer,Los Angeles,California,...,OFF-SU-10001225,Office Supplies,Supplies,Staples,25.760,7,0.0,0.5152,4.91,High
31797,36296,CA-2013-129238,2013-01-31,2013-02-04,Standard Class,SC-20050,Sample Company A,Home Office,Los Angeles,California,...,OFF-PA-10002764,Office Supplies,Paper,Staples,56.700,5,0.0,27.7830,4.73,Medium
33898,38536,CA-2013-101651,2013-12-25,2013-12-31,Standard Class,SC-20305,Sean Christensen,Consumer,San Jose,California,...,OFF-EN-10001990,Office Supplies,Envelopes,Staples,39.760,7,0.0,18.6872,3.95,Medium
34231,33803,CA-2011-143917,2011-07-25,2011-07-27,Second Class,KL-16645,Ken Lonsdale,Consumer,San Francisco,California,...,FUR-FU-10004351,Furniture,Furnishings,Staples,77.920,8,0.0,34.2848,3.84,High
35182,35683,CA-2013-156811,2013-10-28,2013-11-03,Standard Class,BP-11095,Bart Pistole,Corporate,San Francisco,California,...,OFF-AP-10001366,Office Supplies,Appliances,Staples,43.920,4,0.0,11.8584,3.53,Medium
39178,37384,CA-2012-114048,2012-12-14,2012-12-18,Standard Class,EH-13945,Eric Hoffmann,Consumer,Costa Mesa,California,...,FUR-FU-10004351,Furniture,Furnishings,Staples,29.220,3,0.0,12.8568,2.44,Medium
39631,33152,CA-2011-114643,2011-06-13,2011-06-17,Standard Class,FM-14215,Filia McAdams,Corporate,Los Angeles,California,...,OFF-AR-10003631,Office Supplies,Art,Staples,14.520,3,0.0,4.7916,2.33,High
39758,34458,CA-2011-153969,2011-09-21,2011-09-25,Standard Class,HF-14995,Herbert Flentye,Consumer,San Francisco,California,...,OFF-EN-10001539,Office Supplies,Envelopes,Staples,15.560,2,0.0,7.3132,2.30,High
40519,39230,CA-2014-166093,2014-08-18,2014-08-25,Standard Class,RW-19540,Rick Wilson,Corporate,Brentwood,California,...,OFF-EN-10003134,Office Supplies,Envelopes,Staples,23.360,2,0.0,11.6800,2.13,Medium
40566,35713,CA-2011-153983,2011-11-29,2011-12-06,Standard Class,AH-10210,Alan Hwang,Consumer,San Francisco,California,...,OFF-FA-10003495,Office Supplies,Fasteners,Staples,30.400,5,0.0,15.2000,2.12,Medium
40567,38202,US-2014-149006,2014-12-07,2014-12-09,Second Class,BN-11470,Brad Norvell,Corporate,Brentwood,California,...,OFF-ST-10003221,Office Supplies,Storage,Staples,10.680,1,0.0,2.8836,2.12,High
42232,39253,CA-2014-131807,2014-10-06,2014-10-11,Standard Class,GG-14650,Greg Guthrie,Corporate,Chico,California,...,OFF-FA-10002780,Office Supplies,Fasteners,Staples,14.900,5,0.0,6.8540,1.77,Medium
42814,35537,CA-2011-133704,2011-09-20,2011-09-26,Standard Class,MA-17995,Michelle Arnett,Home Office,Los Angeles,California,...,OFF-AP-10001366,Office Supplies,Appliances,Staples,43.920,4,0.0,11.8584,1.65,Medium
43101,38758,US-2012-136987,2012-04-11,2012-04-14,Second Class,AR-10540,Andy Reiter,Consumer,Los Angeles,California,...,OFF-PA-10003127,Office Supplies,Paper,Staples,52.760,2,0.0,24.2696,1.59,Medium
43239,35611,CA-2012-115945,2012-06-25,2012-07-01,Standard Class,AB-10165,Alan Barnes,Consumer,Los Angeles,California,...,OFF-AR-10004062,Office Supplies,Art,Staples,20.960,2,0.0,5.2400,1.56,Medium
44300,36789,CA-2011-105249,2011-11-28,2011-11-28,Same Day,DH-13675,Duane Huffman,Home Office,San Francisco,California,...,OFF-SU-10001225,Office Supplies,Supplies,Staples,7.360,2,0.0,0.1472,1.36,Medium
44579,39966,CA-2012-158918,2012-12-20,2012-12-25,Second Class,AI-10855,Arianne Irving,Consumer,Los Angeles,California,...,OFF-PA-10004947,Office Supplies,Paper,Staples,17.120,4,0.0,7.7040,1.31,Medium
44696,38671,US-2014-123862,2014-01-08,2014-01-10,Second Class,JF-15190,Jamie Frazer,Consumer,Long Beach,California,...,OFF-FA-10003112,Office Supplies,Fasteners,Staples,7.890,1,0.0,3.5505,1.29,High
45188,33356,CA-2011-106439,2011-10-31,2011-11-04,Standard Class,GG-14650,Greg Guthrie,Corporate,Los Angeles,California,...,OFF-FA-10002975,Office Supplies,Fasteners,Staples,11.340,3,0.0,5.2164,1.20,High
45933,33704,CA-2014-144589,2014-01-21,2014-01-26,Standard Class,TM-21010,Tamara Manning,Consumer,San Francisco,California,...,OFF-AR-10003631,Office Supplies,Art,Staples,24.200,5,0.0,7.9860,1.07,Medium
45994,32473,CA-2011-120243,2011-12-27,2011-12-30,Second Class,AT-10435,Alyssa Tate,Home Office,Los Angeles,California,...,OFF-LA-10004425,Office Supplies,Labels,Staples,11.560,4,0.0,5.4332,1.06,High
46676,39072,CA-2011-166961,2011-12-27,2011-12-31,Standard Class,CD-12790,Cynthia Delaney,Home Office,Moreno Valley,California,...,OFF-AP-10001366,Office Supplies,Appliances,Staples,10.980,1,0.0,2.9646,0.95,Medium
46728,33281,CA-2011-164721,2011-11-25,2011-11-27,Second Class,LW-16825,Laurel Workman,Corporate,Brentwood,California,...,FUR-FU-10001940,Furniture,Furnishings,Staples,23.880,3,0.0,10.5072,0.94,High
46855,33684,CA-2012-145065,2012-12-12,2012-12-15,First Class,DK-13375,Dennis Kane,Consumer,San Diego,California,...,OFF-FA-10001229,Office Supplies,Fasteners,Staples,7.860,2,0.0,3.6156,0.92,Medium
46863,37193,CA-2011-168305,2011-11-01,2011-11-08,Standard Class,PL-18925,Paul Lucas,Home Office,Los Angeles,California,...,OFF-PA-10004947,Office Supplies,Paper,Staples,21.400,5,0.0,9.6300,0.92,Medium
47030,33708,CA-2012-142041,2012-06-07,2012-06-09,Second Class,EM-13810,Eleni McCrary,Corporate,Los Angeles,California,...,OFF-BI-10004187,Office Supplies,Binders,Staples,7.520,5,0.2,2.6320,0.89,Medium
47343,32157,CA-2011-133851,2011-06-09,2011-06-16,Standard Class,CM-12445,Chuck Magee,Consumer,San Francisco,California,...,OFF-SU-10001225,Office Supplies,Supplies,Staples,7.360,2,0.0,0.1472,0.84,Low
47945,40793,US-2013-123610,2013-05-13,2013-05-17,Standard Class,VM-21835,Vivian Mathis,Consumer,Mission Viejo,California,...,OFF-AP-10002222,Office Supplies,Appliances,Staples,8.670,1,0.0,2.3409,0.74,Medium
48643,38919,US-2011-144078,2011-11-25,2011-11-29,Standard Class,RB-19435,Richard Bierner,Consumer,Los Angeles,California,...,OFF-AR-10004707,Office Supplies,Art,Staples,7.440,3,0.0,2.6040,0.62,Medium
49586,33645,CA-2014-109701,2014-12-03,2014-12-04,Same Day,AM-10360,Alice McCarthy,Corporate,Los Angeles,California,...,OFF-BI-10004187,Office Supplies,Binders,Staples,9.024,6,0.2,3.1584,0.44,High
49694,37196,CA-2014-108000,2014-01-13,2014-01-17,Standard Class,LS-16945,Linda Southworth,Corporate,San Francisco,California,...,OFF-EN-10002621,Office Supplies,Envelopes,Staples,9.780,1,0.0,4.8900,0.42,Medium
50193,35706,US-2011-154879,2011-05-06,2011-05-11,Standard Class,SN-20710,Steve Nguyen,Home Office,Los Angeles,California,...,OFF-LA-10004425,Office Supplies,Labels,Staples,5.780,2,0.0,2.7166,0.33,Medium
50357,39073,CA-2011-166961,2011-12-27,2011-12-31,Standard Class,CD-12790,Cynthia Delaney,Home Office,Moreno Valley,California,...,OFF-FA-10003485,Office Supplies,Fasteners,Staples,7.860,3,0.0,3.6156,0.30,Medium
50394,33000,CA-2011-139857,2011-02-03,2011-02-07,Standard Class,CD-12790,Cynthia Delaney,Home Office,San Diego,California,...,OFF-FA-10001843,Office Supplies,Fasteners,Staples,12.350,5,0.0,5.8045,0.29,Medium
50623,41180,CA-2011-112291,2011-04-03,2011-04-08,Standard Class,KE-16420,Katrina Edelman,Corporate,Los Angeles,California,...,OFF-EN-10001415,Office Supplies,Envelopes,Staples,11.160,2,0.0,5.5800,0.24,Medium

In [17]:
df[(df["Profit"]>1000) & (df["Sales"]>1000)]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
8,40155,CA-2014-135909,2014-10-14,2014-10-21,Standard Class,JW-15220,Jane Waco,Corporate,Sacramento,California,...,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,5083.96,5,0.2,1906.4850,867.69000,Low
12,45794,SA-2011-1830,2011-12-27,2011-12-29,Second Class,MM-7260,Magdelene Morse,Consumer,Jizan,Jizan,...,TEC-CIS-10001717,Technology,Phones,"Cisco Smart Phone, with Caller ID",2616.96,4,0.0,1151.4000,832.41000,Critical
14,27704,IN-2013-73951,2013-06-06,2013-06-08,Second Class,PF-19120,Peter Fuller,Consumer,Mudanjiang,Heilongjiang,...,OFF-AP-10003500,Office Supplies,Appliances,"KitchenAid Microwave, White",3701.52,12,0.0,1036.0800,804.54000,Critical
17,12069,ES-2014-1651774,2014-09-08,2014-09-14,Standard Class,PJ-18835,Patrick Jones,Corporate,Prato,Tuscany,...,OFF-AP-10004512,Office Supplies,Appliances,"Hoover Stove, Red",7958.58,14,0.0,3979.0800,778.32000,Low
23,13528,ES-2013-2860574,2013-02-27,2013-03-01,Second Class,LB-16795,Laurel Beltran,Home Office,Edinburgh,Scotland,...,OFF-AP-10003590,Office Supplies,Appliances,"KitchenAid Refrigerator, Black",5273.70,10,0.0,1898.4000,730.91000,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13013,23447,IN-2011-77892,2011-04-02,2011-04-08,Standard Class,HL-15040,Hunter Lopez,Consumer,Rajshahi,Rajshahi,...,TEC-PH-10001751,Technology,Phones,"Samsung Smart Phone, Cordless",3195.00,5,0.0,1150.2000,23.95000,Medium
14843,39450,CA-2014-140151,2014-03-24,2014-03-26,First Class,RB-19360,Raymond Buch,Consumer,Seattle,Washington,...,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.96,4,0.0,6719.9808,20.00054,Medium
16062,39785,CA-2013-158841,2013-02-02,2013-02-04,Second Class,SE-20110,Sanjit Engle,Consumer,Arlington,Virginia,...,TEC-MA-10001127,Technology,Machines,HP Designjet T520 Inkjet Large Format Printer ...,8749.95,5,0.0,2799.9840,17.83000,Critical
19307,21850,IN-2011-50060,2011-09-06,2011-09-13,Standard Class,MC-17575,Matt Collins,Consumer,Yancheng,Jiangsu,...,FUR-BO-10000035,Furniture,Bookcases,"Dania Classic Bookcase, Pine",2472.66,6,0.0,1038.4200,13.25000,Medium
39564,12383,ES-2012-5671193,2012-05-29,2012-05-29,Same Day,MG-18145,Mike Gockenbach,Consumer,Luton,England,...,TEC-PH-10004823,Technology,Phones,"Nokia Smart Phone, Full Size",5724.54,9,0.0,2461.3200,2.34000,Medium